[BSPlayer.Skin]
Version=1.00

[Settings]
; 0 - Two separate windows, one movie window the other with controls (skinned)
; 1 - One window only (not fully supported yet)
SkinType=0
; File name of the main image
MainImg=Main.bmp

;0-Normal
;1-Skin can be any shape, pixel at top left corner (position 0,0) is transparent color
MainAnySape=0
Ext=.bmp

;Load specified font
;
;LoadFont1=MyFont.ttf
;LoadFont2=AnotherFont.ttf

; Button definitions
; BtnX=<name>,xpos,ypos,<type>,<action>[;<Description>]
; <name>   - this is file name of the image for button
;            Image files must be named name[n|d|u].bmp
;            n=normal, d=button down, u=mouse over
; xpos     - X position
; ypos     - Y postion
; <type>   - Button type
;             0-Normal buttons
;             1-Shaped buttons
;             2-Transparent (currently not supported in full screen skins)
;             3-Blend (not supported yet)
; <action> - All commands from bsp.h/bsp.pas, search for 'Other commands'
; <Description>
; Version 1.00.808+, it's now possible to use messages from language file for descriptions
; Syntax: $lang.SECTION.KEY
; Ex.: Btn18=b3,208,86,0,34;$lang.Menu.81
;      Btn20=mute,323,75,0,35;$lang.Actions.36
[Buttons]
;Number of buttons
Number=8
Btn1=open,9,53,0,63;$lang.Menu.1
Btn2=list,40,53,0,34;$lang.Menu.81
Btn3=pause,120,53,0,21;$lang.Menu.11
Btn4=play,151,53,0,20;$lang.Menu.10
Btn5=stop,198,53,0,22;$lang.Menu.12
Btn6=prev,229,53,0,25;$lang.Menu.9
Btn7=next,260,53,0,28;$lang.Menu.13
Btn8=exit,780,5,0,77;$lang.Menu.82
;Btn9=pchap,56,86,0,26;$lang.Menu.14
;Btn10=nchap,87,86,0,29;$lang.Menu.15


[Display]
; x,y;<font name>,<size>,<style>;<Font color>
; style can be N - Nornal font
;              B - Bold
;              I - Italic
;              U - Underline
; or combination of above, for ex. Bold italic -> BI

; Movie title/file name
Title=11,9;Arial,9,B;000000
; Max width of title, if it's longer it will be scrolled
MaxTitleWidth=400

;Version=253,88;Arial,8,B;71964F
Subs=10,25;Arial,7,N;000000
MaxSubsWidth=400

MovTimeLen=410,9;Arial,10,B;000000
sRepeat=410,25;Arial,7,N;000000

Status=624,9;Arial,9,B;000000
MovInfo=624,22;Arial,9,N;000000

[TrackBar]
; Position and size
; x,y,w,h (w,h is ignored if TrackKind=HB,VB)
PosSize=7,42,786,7

; Track bar kind, 
;  H-Horizontal, V-Vertical, HB-Custom bitmap horizontal, VB-Custom bitmap vertical
;  HBtn - button Horizontal, VBtn - button Vertical
Kind=H

;If TrackKind=HB, name of the bitmap that will be used
Bitmap=seek.bmp

; If HBtn or VBtn
;ButtonImg=VolBtn.bmp

//Set this to 1 for transparent background
TransparentBg=1

Border=1
BorderColor=000000
; Ignored for HB,VB
Color=313A31
MouseOverColor=555555
BackColor=000000



; same parameters as TrackBar
[Volume]
PosSize=466,54,60,32
Kind=HB
Bitmap=volume.bmp
TransparentBg=1

[GUI]
MenuBackClr=6995B8
MenuBackClrIco=234F7C
MenuSelBackClr=E3F7F8
MenuFontClr=000000
MenuSelFontClr=000000
MenuDisFontClr=BF803F
MenuSeparatorClr=3F502B
PlayListBackClr=0C76A2
PlayListTextClr=000000
PlayListActTextClr=FFFFFF

[Text]
Author=TinaZ, tina@webteh.com
URL=
Description=Base skin
